# Generated by Django 5.2.6 on 2026-03-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="roll_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="student_name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
