# Generated by Django 5.2.6 on 2026-04-17 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_project_status_alter_project_title_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["category", "status"], name="projects_pr_categor_b7ef12_idx"
            ),
        ),
    ]
